---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Introduction: ggplot package





# Example using ggplot

# learning ggnanimate

library(tidyverse)
library(gapminder)
library(ggplot2)
library(gganimate)


# Generate average life expectancy per country

gapminder %>% 
  group_by(country) %>% 
  summarize(av.le = mean(lifeExp)) %>% 
  arrange(desc(av.le))


# Generate average per capita GDP

gapminder %>% 
  group_by(country) %>% 
summarize(av.income = mean(gdpPercap))

# Generate a box plot per continent (Life Expectancy variable)

gapminder %>% 
  ggplot(aes(x = factor(0), y = lifeExp)) + 
  geom_boxplot(aes(color = continent)) +
  facet_wrap(~continent)


# Generate a scatter plot with life expectancy and gross domestic product per capita

gapminder %>% ggplot(aes(x = log(gdpPercap), y = lifeExp, col = continent)) +
  geom_point()


# Generate a regression line with geom_smooth and title

gapminder %>% ggplot(aes(x = log(gdpPercap), y = lifeExp)) +
  geom_point() + geom_smooth(lwd = 1, se = TRUE, method = 'lm') + ggtitle('GDP per capita vs. Life Expectancy')

# Let us take a look at the graph following the Economist's frame

library(ggthemes)
gapminder %>% ggplot(aes(x = log(gdpPercap), y = lifeExp)) +
geom_point() + geom_smooth(lwd = 1, se = TRUE, method = 'lm') + theme_economist() + ggtitle('GDP per capita vs. Life Expectancy')